<a href="https://colab.research.google.com/github/JustynaGoc/machine-learning-bootcamp/blob/main/01_Regresja_liniowa_rownanie_normalne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np

In [18]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000,3250,3500,3750,4000,4250])
X1,Y

(array([1, 2, 3, 4, 5, 6]), array([3000, 3250, 3500, 3750, 4000, 4250]))

In [19]:
m = len(X1)
print(f'Lata pracy: {X1}')
print(f'Wynagrodzenie: {Y}')
print(f'Liczba probek: {m}')

Lata pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba probek: 6


In [20]:
X1=X1.reshape(m,1)
X1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [21]:
bias = np.ones((m,1))
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [22]:
X = np.append(bias,X1,axis=1)
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

In [23]:
np.dot(X.T, X)

array([[ 6., 21.],
       [21., 91.]])

In [24]:
L = np.linalg.inv(np.dot(X.T, X))
L

array([[ 0.86666667, -0.2       ],
       [-0.2       ,  0.05714286]])

In [28]:
P=np.dot(X.T,Y)
P

array([21750., 80500.])

In [29]:
np.dot(L,P)

array([2750.,  250.])

59

sklearn

In [33]:
from sklearn.linear_model import LinearRegression


In [35]:
regression = LinearRegression()
regression.fit(X1,Y)

LinearRegression()

In [37]:
regression.intercept_

np.float64(2750.0)

In [39]:
regression.coef_[0]

np.float64(250.0)