<a href="https://colab.research.google.com/github/JustynaGoc/machine-learning-bootcamp/blob/main/02_Regresja_liniowa_spadek_wzdluz_gradientu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
import numpy as np
import sklearn
import plotly.express as px
np.random.seed(42)

Wygenerowanie danych

In [24]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000,3250,3500,3750,4000,4250])
m = len(X1)

In [25]:
print(f'Lata  pracy: {X1}')
print(f'Wynagrodzenie: {y}')
print(f'Liczba lat: {m}')

Lata  pracy: [1 2 3 4 5 6]
Wynagrodzenie: [3000 3250 3500 3750 4000 4250]
Liczba lat: 6


Przygotowanie danych

In [26]:
X1= X1.reshape(m,1)
X1

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [27]:
bias = np.ones((m,1))

In [28]:
X = np.append(bias, X1, axis = 1)
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

Losowa inicjacja parametrow

In [29]:
eta = 0.01
weights = np.random.randn(2,1)
print(X), print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[ 0.49671415]
 [-0.1382643 ]]


(None, None)

In [19]:
Y

array([3000, 3250, 3500, 3750, 4000, 4250])

Metoda gradientu prostego

In [20]:
intercept =[]
coef = []

In [22]:
intercept = []
coef = []

for i in range(3000):
    gradient = (2 / m) * X.T.dot(X.dot(weights) - Y)
    weights = weights - eta * gradient
    intercept.append(weights[0][0])
    coef.append(weights[1][0])

print(weights)


[[ 60.49645837  65.49645837  70.49645837  75.49645837  80.49645837
   85.49645837]
 [209.86890588 227.36890588 244.86890588 262.36890588 279.86890588
  297.36890588]]
