<a href="https://colab.research.google.com/github/JustynaGoc/machine-learning-bootcamp/blob/main/1_Czyszczenie_danych.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Przygotowanie danych do uczenie maszynowego - data processuing

In [1]:
##Importowanie bibliotek

In [2]:
import pandas as pd
import numpy as np
import sklearn
sklearn.__version__


'1.6.1'

In [3]:
##Tworzenie zbioru do ćwiczeń

In [4]:
data = {
    "size" :  ["XL", "L", "M", "L", "M"],
    "color":  ["red", "green", "blue", "green", "red"],
    "gender": ["female", "male", "male", "female", "female"],
    "price":  [199.0, 89.0, 99.0, 129.0,  79.0],
    "weight": [500, 450, 300, 380, 410],
    "bought": ["yes", "no", "yes", "no", "yes"]
}
df_raw = pd.DataFrame(data)
df_raw

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [5]:
##utworzenie kopii zapasowej

In [6]:
df = df_raw.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   size    5 non-null      object 
 1   color   5 non-null      object 
 2   gender  5 non-null      object 
 3   price   5 non-null      float64
 4   weight  5 non-null      int64  
 5   bought  5 non-null      object 
dtypes: float64(1), int64(1), object(4)
memory usage: 372.0+ bytes


In [7]:
##zmiana typy danych  i wstepna eksploracja

In [8]:
for col in ["size", "color", "gender", "bought"]:
  df[col] = df[col].astype('category')

df["weight"]= df["weight"].astype(float)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   size    5 non-null      category
 1   color   5 non-null      category
 2   gender  5 non-null      category
 3   price   5 non-null      float64 
 4   weight  5 non-null      float64 
 5   bought  5 non-null      category
dtypes: category(4), float64(2)
memory usage: 744.0 bytes


In [9]:
df.describe().T
#domyślnie  tylko  dla kolumn liczbowych
# .T  transponuje dane na bardziej czytelny  format

count   mean        std    min    25%    50%    75%    max
price     5.0  119.0  48.476799   79.0   89.0   99.0  129.0  199.0
weight    5.0  408.0  75.299402  300.0  380.0  410.0  450.0  500.0

In [10]:
df.describe(include =["category"]).T
#statystyki dala  kolumn kategorycznych

count unique     top freq
size       5      3       L    2
color      5      3   green    2
gender     5      2  female    3
bought     5      2     yes    3

In [11]:
#Label Encoder - mapowanie  na 0/1 - zmienna docelowa /targerowa

In [12]:
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [13]:
from sklearn.preprocessing  import LabelEncoder

In [14]:
le = LabelEncoder()
le.fit(df["bought"])
le.transform(df["bought"])

array([1, 0, 1, 0, 1])

In [15]:
le.fit_transform(df["bought"])
le.classes_

array(['no', 'yes'], dtype=object)

In [16]:
df["bought"]=le.fit_transform(df["bought"])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [34]:
## powrot do pierwotnej postaci
le.inverse_transform(df["bought"])
df["bought"]=le.inverse_transform(df["bought"])
df

size  color  gender  price  weight bought
0   XL    red  female  199.0   500.0    yes
1    L  green    male   89.0   450.0     no
2    M   blue    male   99.0   300.0    yes
3    L  green  female  129.0   380.0     no
4    M    red  female   79.0   410.0    yes

In [18]:
##OneHotEncoder  - zmienne opisujace

In [24]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
encoder.fit(df[['size']])

OneHotEncoder(sparse_output=False)

In [25]:
encoder.transform(df[["size"]])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [27]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [28]:
##usuwanie jednego wymiaru, aby zbyt nie dopasowac  model|


In [30]:
encoder = OneHotEncoder(drop = "first", sparse_output = False)
encoder.fit(df[["size"]])
encoder.transform(df[["size"]])

array([[0., 1.],
       [0., 0.],
       [1., 0.],
       [0., 0.],
       [1., 0.]])

In [31]:
encoder.categories_

[array(['L', 'M', 'XL'], dtype=object)]

In [32]:
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0   500.0       1
1    L  green    male   89.0   450.0       0
2    M   blue    male   99.0   300.0       1
3    L  green  female  129.0   380.0       0
4    M    red  female   79.0   410.0       1

In [33]:
# Pandas get_dummies()

In [35]:
pd.get_dummies(df)

price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0   500.0   False   False     True       False        False       True   
1   89.0   450.0    True   False    False       False         True      False   
2   99.0   300.0   False    True    False        True        False      False   
3  129.0   380.0    True   False    False       False         True      False   
4   79.0   410.0   False    True    False       False        False       True   

   gender_female  gender_male  bought_no  bought_yes  
0           True        False      False        True  
1          False         True       True       False  
2          False         True      False        True  
3           True        False       True       False  
4           True        False      False        True

In [36]:
pd.get_dummies(df, dtype = int)

price  weight  size_L  size_M  size_XL  color_blue  color_green  color_red  \
0  199.0   500.0       0       0        1           0            0          1   
1   89.0   450.0       1       0        0           0            1          0   
2   99.0   300.0       0       1        0           1            0          0   
3  129.0   380.0       1       0        0           0            1          0   
4   79.0   410.0       0       1        0           0            0          1   

   gender_female  gender_male  bought_no  bought_yes  
0              1            0          0           1  
1              0            1          1           0  
2              0            1          0           1  
3              1            0          1           0  
4              1            0          0           1

In [37]:
pd.get_dummies(df, dtype = int, drop_first=True)

price  weight  size_M  size_XL  color_green  color_red  gender_male  \
0  199.0   500.0       0        1            0          1            0   
1   89.0   450.0       0        0            1          0            1   
2   99.0   300.0       1        0            0          0            1   
3  129.0   380.0       0        0            1          0            0   
4   79.0   410.0       1        0            0          1            0   

   bought_yes  
0           1  
1           0  
2           1  
3           0  
4           1

In [38]:
pd.get_dummies(df, dtype = int, drop_first=True)

price  weight  new_M  new_XL  new_green  new_red  new_male  new_yes
0  199.0   500.0      0       1          0        1         0        1
1   89.0   450.0      0       0          1        0         1        0
2   99.0   300.0      1       0          0        0         1        1
3  129.0   380.0      0       0          1        0         0        0
4   79.0   410.0      1       0          0        1         0        1

In [39]:
pd.get_dummies(df, dtype = int, drop_first=True, columns=["size"])


color  gender  price  weight bought  size_M  size_XL
0    red  female  199.0   500.0    yes       0        1
1  green    male   89.0   450.0     no       0        0
2   blue    male   99.0   300.0    yes       1        0
3  green  female  129.0   380.0     no       0        0
4    red  female   79.0   410.0    yes       1        0

In [43]:
##Standaryzacja StandardScaler

In [42]:
##std() = nandas nieobciążony- dzieli przez N-1
##std() - numpy obciążony - dzieli przez N

In [47]:
print(f"{df["price"]}\n")
print(f"Średinia pandas : {df["price"].mean()}")
print(f"Odchylenie standardowe pandas : {df["price"].std()}")

print(f"Średinia numpy: {np.mean(df["price"])}")
print(f"Odchylenie standardowej:numpy {np.std(df["price"])}")

0    199.0
1     89.0
2     99.0
3    129.0
4     79.0
Name: price, dtype: float64

Średinia pandas : 119.0
Odchylenie standardowe pandas : 48.47679857416329
Średinia numpy: 119.0
Odchylenie standardowej:numpy 43.3589667773576


In [48]:
(df['price'] -df['price'].mean()) /df['price'].std()

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [49]:
def standardize(x):
  return(x - x.mean())/x.std()
standardize(df["price"])

0    1.650274
1   -0.618853
2   -0.412568
3    0.206284
4   -0.825137
Name: price, dtype: float64

In [53]:
def standardize(x):
  return(x - np.mean(x))/np.std(x)
standardize(df["price"])

0    1.845062
1   -0.691898
2   -0.461266
3    0.230633
4   -0.922531
Name: price, dtype: float64

In [51]:
##Scale

In [52]:
from sklearn.preprocessing import scale
scale(df["price"])

array([ 1.84506242, -0.69189841, -0.4612656 ,  0.2306328 , -0.92253121])

In [54]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(df[["price"]])
scaler.transform(df[["price"]])

array([[ 1.84506242],
       [-0.69189841],
       [-0.4612656 ],
       [ 0.2306328 ],
       [-0.92253121]])

In [56]:
scaler_price  = StandardScaler()
df["price"]= scaler_price.fit_transform(df[["price"]])
weight_price  = StandardScaler()
df["weight"]= scaler_price.fit_transform(df[["weight"]])
df

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

In [58]:
scaler = StandardScaler()
df[["price", "weight"]]= scaler.fit_transform(df[["price", "weight"]])
df

size  color  gender     price    weight bought
0   XL    red  female  1.845062  1.366002    yes
1    L  green    male -0.691898  0.623610     no
2    M   blue    male -0.461266 -1.603567    yes
3    L  green  female  0.230633 -0.415740     no
4    M    red  female -0.922531  0.029696    yes

In [67]:
#Przygoowanie danych do modelu - całość

In [69]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.preprocessing import LabelEncoder
#from sklearn.preprocessing import OneHotEncoder - szybsze pd.get_dummmies()
from sklearn.preprocessing import StandardScaler


In [62]:
df = df_raw.copy()
df

size  color  gender  price  weight bought
0   XL    red  female  199.0     500    yes
1    L  green    male   89.0     450     no
2    M   blue    male   99.0     300    yes
3    L  green  female  129.0     380     no
4    M    red  female   79.0     410    yes

In [64]:
le= LabelEncoder()
df["bought"] = le.fit_transform(df["bought"])
df

size  color  gender  price  weight  bought
0   XL    red  female  199.0     500       1
1    L  green    male   89.0     450       0
2    M   blue    male   99.0     300       1
3    L  green  female  129.0     380       0
4    M    red  female   79.0     410       1

In [65]:
scaler = StandardScaler()
df[["price","weight"]]= scaler.fit_transform(df[["price","weight"]])
df

size  color  gender     price    weight  bought
0   XL    red  female  1.845062  1.366002       1
1    L  green    male -0.691898  0.623610       0
2    M   blue    male -0.461266 -1.603567       1
3    L  green  female  0.230633 -0.415740       0
4    M    red  female -0.922531  0.029696       1

In [66]:
df=pd.get_dummies(df, drop_first = True, dtype = int)
df

price    weight  bought  size_M  size_XL  color_green  color_red  \
0  1.845062  1.366002       1       0        1            0          1   
1 -0.691898  0.623610       0       0        0            1          0   
2 -0.461266 -1.603567       1       1        0            0          0   
3  0.230633 -0.415740       0       0        0            1          0   
4 -0.922531  0.029696       1       1        0            0          1   

   gender_male  
0            0  
1            1  
2            1  
3            0  
4            0