<a href="https://colab.research.google.com/github/JustynaGoc/machine-learning-bootcamp/blob/main/Supervised/02_gradient_descent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Regresja liniowa -spadek wzdłóż gradien

In [ ]:
import numpy as np
import pandas as pd
import sklearn

In [ ]:
X1 = np.array([1,2,3,4,5,6])
Y = np.array([3000,3250,3500,3750,4000,4250])
X1 = X1.reshape(-1,1)
m = len(X1)

In [ ]:
bias = np.ones((m,1))
bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [ ]:
X = np.append(bias, X1, axis = 1)
X

array([[1., 1.],
       [1., 2.],
       [1., 3.],
       [1., 4.],
       [1., 5.],
       [1., 6.]])

## Losowa inicjalizacja parametrów

In [ ]:
eta = 0.01
weights = np.random.randn(2, 1)
print(X)
print(weights)

[[1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]]
[[ 1.25215809]
 [-0.13738854]]


## Metoda Gradientu prostego

In [ ]:
intercept = []
coef = []

for i in range(3000):
    gradient = (2 / m) * X.T.dot(X.dot(weights) - Y)
    weights = weights - eta * gradient
    intercept.append(weights[0][0])
    coef.append(weights[1][0])

In [ ]:
df = pd.DataFrame( data ={'intercept' : intercept,
                          'coef' :   coef })
df.head()

,intercept,coef
0,61.236732,209.816635
1,105.324833,351.885684
2,138.586338,447.774288
3,164.470412,512.248377
4,185.323617,555.353441


## Wizualizacja dopasowania

In [ ]:
import plotly.express as px


In [ ]:
px.line(df, y = 'intercept', width = 800, title = 'Dopasowanie intercept')

In [ ]:
px.line(df, y = 'coef', width = 800, title = 'Dopasowanie coef')